name: campusbite
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.4
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  sizer: ^3.0.5
  fl_chart: ^1.0.0
  google_fonts: ^6.1.0
  web: any
  speech_to_text: ^7.1.0
  firebase_auth: ^5.6.2
  flutterfire_cli: ^1.3.1
  firebase_core: 3.15.1
  google_sign_in: ^6.2.1
  firebase_analytics: ^11.5.2
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^5.0.0
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
