// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB18SS9-rqgwkPLy2vX_n8EKFvL9ONXfsk',
    appId: '1:261779044507:web:6ac3332011ceccb3ef6e3e',
    messagingSenderId: '261779044507',
    projectId: 'zapit-d44be',
    authDomain: 'zapit-d44be.firebaseapp.com',
    storageBucket: 'zapit-d44be.firebasestorage.app',
    measurementId: 'G-993RW8M02V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyw0Elp2nqvVnUoq177zNax6n5eap32Dk',
    appId: '1:261779044507:android:2f8a3c5b05e72ad2ef6e3e',
    messagingSenderId: '261779044507',
    projectId: 'zapit-d44be',
    storageBucket: 'zapit-d44be.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB18SS9-rqgwkPLy2vX_n8EKFvL9ONXfsk',
    appId: '1:261779044507:web:258c481ae495de4aef6e3e',
    messagingSenderId: '261779044507',
    projectId: 'zapit-d44be',
    authDomain: 'zapit-d44be.firebaseapp.com',
    storageBucket: 'zapit-d44be.firebasestorage.app',
    measurementId: 'G-FG1HWXESFP',
  );
}
